apiVersion: v1
kind: Template
labels:
  app: jenkins-agent-dind
  template: jenkins-agent-dind-buildconfig-with-secret
metadata:
  annotations:
    description: Jenkins Agent Docker Image - BuildConfig with Secret
      see https://github.com/faust64/docker-jenkins-agent-dind
    iconClass: icon-openshift
    openshift.io/display-name: Jenkins Agent Docker
    tags: jenkins-agent-dind
  name: jenkins-agent-dind-buildconfig-with-secret
objects:
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      template.openshift.io/expose-username: "{.data['username']}"
    name: git-jadk-${JADK_REPOSITORY_REF}
  stringData:
    username: "${GIT_DEPLOYMENT_TOKEN}"
- apiVersion: v1
  kind: BuildConfig
  metadata:
    annotations:
      description: Builds Jenkins Agent Docker images
    labels:
      name: jadk-${JADK_REPOSITORY_REF}
    name: jadk-${JADK_REPOSITORY_REF}
  spec:
    failedBuildsHistoryLimit: 1
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
    source:
      contextDir: /
      git:
        uri: ${JADK_REPOSITORY_URL}
        ref: "${JADK_REPOSITORY_REF}"
      sourceSecret:
        name: git-jadk-${JADK_REPOSITORY_REF}
      type: Git
    strategy:
      type: Docker
      dockerStrategy:
        env:
        - name: DO_UPGRADE
          value: foo
        forcePull: false
    output:
      to:
        kind: ImageStreamTag
        name: jenkins-agent-dind:${JADK_REPOSITORY_REF}
    triggers:
    - type: ConfigChange
parameters:
- name: GIT_DEPLOYMENT_TOKEN
  description: Git deployment token
  displayName: Git Deployment Token
  required: true
- name: JADK_REPOSITORY_REF
  description: Set this to a branch name, tag or other ref of your repository if you are not using the default branch
  displayName: Git Reference
  required: true
  value: master
- name: JADK_REPOSITORY_URL
  description: The URL of the repository with your Jenkins Agent Docker Dockerfile
  displayName: Git Repository URL
  required: true
  value: https://github.com/faust64/docker-jenkins-agent-dind.git
