apiVersion: v1
kind: Template
labels:
  app: jenkins-agent-dind
  template: jenkins-agent-dind-imagestream
metadata:
  annotations:
    description: Jenkins Agent Docker Image - ImageStream
      see https://github.com/faust64/docker-jenkins-agent-dind
    iconClass: icon-openshift
    openshift.io/display-name: Jenkins Agent Docker
    tags: jenkins-agent-dind
  name: jenkins-agent-dind-imagestream
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      description: Keeps track of changes in Jenkins Docker Agent image
    name: jenkins-agent-dind
